import Head from "next/head";
import Navbar from "../navbar";
import styles from "../layout/styles.module.css";
import DeskNavbar from "../desk-navbar";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>The Question</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.desktopnavbar}>
          <DeskNavbar />
        </div>
        <div className={styles.main}>{children}</div>
        <div className={styles.navbar}>
          <Navbar />
        </div>
      </div>
    </>
  );
};

export default Layout;
